
INSERT INTO TYPE (NAME) VALUES ('Type 1');
INSERT INTO TYPE (NAME) VALUES ('Type 2');

INSERT INTO PROJECT (NAME, DESCRIPTION, START_DATE, END_DATE, TYPE_ID) 
VALUES ('Example Project 1', 'Example Description 1', null, null, SELECT ID FROM TYPE WHERE NAME = 'Type 1');
INSERT INTO PROJECT (NAME, DESCRIPTION, START_DATE, END_DATE, TYPE_ID) 
VALUES ('Example Project 2', 'Example Description 2', null, null, SELECT ID FROM TYPE WHERE NAME = 'Type 2');

INSERT INTO TASK (PROJECT_ID, NAME, DESCRIPTION, START_DATE, END_DATE, LOE)
VALUES (SELECT ID FROM PROJECT WHERE NAME = 'Example Project 1', 'Example Task 1', 'Example Description 1', null, null, 1);
INSERT INTO TASK (PROJECT_ID, NAME, DESCRIPTION, START_DATE, END_DATE, LOE)
VALUES (SELECT ID FROM PROJECT WHERE NAME = 'Example Project 1', 'Example Task 2', 'Example Description 2', null, null, 2);

INSERT INTO TASK (PROJECT_ID, NAME, DESCRIPTION, START_DATE, END_DATE, LOE)
VALUES (SELECT ID FROM PROJECT WHERE NAME = 'Example Project 1', 'Example Task 3', 'Example Description 3', null, null, 3);
INSERT INTO TASK (PROJECT_ID, NAME, DESCRIPTION, START_DATE, END_DATE, LOE)
VALUES (SELECT ID FROM PROJECT WHERE NAME = 'Example Project 1', 'Example Task 4', 'Example Description 4', null, null, 4);

INSERT INTO PART (TYPE_ID, MANUFACTURER, NAME, NUMBER, DESCRIPTION, WEIGHT, COST)
VALUES (SELECT ID FROM TYPE WHERE NAME = 'Type 1', 'Example Manufacturer 1', 'Example Part 1', 'Example Number 1', 'Example Description 1', 0.0, 1.00);
INSERT INTO PART (TYPE_ID, MANUFACTURER, NAME, NUMBER, DESCRIPTION, WEIGHT, COST)
VALUES (SELECT ID FROM TYPE WHERE NAME = 'Type 2', 'Example Manufacturer 2', 'Example Part 2', 'Example Number 2', 'Example Description 2', 0.0, 1.00);
INSERT INTO PART (TYPE_ID, MANUFACTURER, NAME, NUMBER, DESCRIPTION, WEIGHT, COST)
VALUES (SELECT ID FROM TYPE WHERE NAME = 'Type 1', 'Example Manufacturer 3', 'Example Part 3', 'Example Number 3', 'Example Description 3', 0.0, 1.00);

INSERT INTO TASK_PART (TASK_ID, PART_ID) 
VALUES (SELECT ID FROM TASK WHERE NAME = 'Example Task 1', SELECT ID FROM PART WHERE NAME = 'Example Part 1');
INSERT INTO TASK_PART (TASK_ID, PART_ID) 
VALUES (SELECT ID FROM TASK WHERE NAME = 'Example Task 1', SELECT ID FROM PART WHERE NAME = 'Example Part 2');
INSERT INTO TASK_PART (TASK_ID, PART_ID) 
VALUES (SELECT ID FROM TASK WHERE NAME = 'Example Task 3', SELECT ID FROM PART WHERE NAME = 'Example Part 2');
INSERT INTO TASK_PART (TASK_ID, PART_ID) 
VALUES (SELECT ID FROM TASK WHERE NAME = 'Example Task 3', SELECT ID FROM PART WHERE NAME = 'Example Part 3');
