
-- DROP SCHEMA TO RE-CREATE
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS TYPE;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS PART;
DROP TABLE IF EXISTS TASK_PART;

-- CREATE SCHEMA
CREATE TABLE TYPE (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(1024) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PROJECT (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(1024) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	START_DATE DATETIME,
	END_DATE DATETIME,
	TYPE_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (TYPE_ID) REFERENCES TYPE(ID)
);

CREATE TABLE TASK (
	ID INT NOT NULL AUTO_INCREMENT,
	PROJECT_ID INT NOT NULL,
	NAME VARCHAR(1024) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	START_DATE DATETIME,
	END_DATE DATETIME,
	LOE INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE PART (
	ID INT NOT NULL AUTO_INCREMENT,
	TYPE_ID INT NOT NULL,
	MANUFACTURER VARCHAR(1024) NOT NULL,
	NAME VARCHAR(1024) NOT NULL,
	NUMBER VARCHAR(1024) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	WEIGHT FLOAT,
	COST FLOAT,
	PRIMARY KEY (ID),
	FOREIGN KEY (TYPE_ID) REFERENCES TYPE(ID)
);

CREATE TABLE TASK_PART (
	ID INT NOT NULL AUTO_INCREMENT,
	TASK_ID INT NOT NULL,
	PART_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
	FOREIGN KEY (PART_ID) REFERENCES PART(ID)
);