
-- USER MANAGEMENT
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE USERS (
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(128) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	ENABLED BIT NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE USER_ROLES (
	ID INT NOT NULL AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	AUTHORITY VARCHAR(128) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_USERS_ROLES FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- DROP SCHEMA TO RE-CREATE
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS TYPE;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS PART;
DROP TABLE IF EXISTS TASK_PART;

-- CREATE SCHEMA
CREATE TABLE TYPE (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(1024) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PROJECT (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(1024) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	START_DATE DATETIME,
	END_DATE DATETIME,
	TYPE_ID INT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_TYPE_PROJECT FOREIGN KEY (TYPE_ID) REFERENCES TYPE(ID)
);

CREATE TABLE TASK (
	ID INT NOT NULL AUTO_INCREMENT,
	PROJECT_ID INT NOT NULL,
	NAME VARCHAR(1024) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	START_DATE DATETIME,
	END_DATE DATETIME,
	LOE INT,
	PRIMARY KEY (ID),
	CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE PART (
	ID INT NOT NULL AUTO_INCREMENT,
	TYPE_ID INT NOT NULL,
	MANUFACTURER VARCHAR(1024) NOT NULL,
	NAME VARCHAR(1024) NOT NULL,
	NUMBER VARCHAR(1024) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	WEIGHT FLOAT,
	COST FLOAT,
	PRIMARY KEY (ID),
	CONSTRAINT FK_PART_TYPE FOREIGN KEY (TYPE_ID) REFERENCES TYPE(ID)
);

CREATE TABLE TASK_PART (
	ID INT NOT NULL AUTO_INCREMENT,
	TASK_ID INT NOT NULL,
	PART_ID INT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_TASKPART_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
	CONSTRAINT FK_TASKPART_PART FOREIGN KEY (PART_ID) REFERENCES PART(ID)
);
